### PR TITLE
Add option to export loop as video

### PR DESCRIPTION
**Pull request by ernstwi**
This is a bigger change than my last two PRs, and it's fine if you don't think it fits in giffer.

The natural key to bind it to would be v, but that's already taken in mpv's default bindings. Also, I had to change the "output file" script argument to "output dir", since I wanted to keep the extension of the input video. A bit clunky.

Cheers!

### CODE REVIEW

**Comment by defaultxr** [comment]
Thanks for this (and your other two PRs)! Actually, I was thinking of eventually adding an option for the output format originally but never got around to it, so I think this does fit in the project.

The only improvement I think could be made to this PR is that it should be possible to keep the invocation of the script the same, and just detect the output format based on the file extension, rather than having to specify `gif` or `video` separately. So `output.gif` would result in gif output and any other extension would create a video matching that extension, of course. But if the output-file argument is the name of a directory, then we assume the user wants the same filename and extension as output, just in the specified directory. That way your use case (keeping the same extension/file type) would still be possible without adding an extra argument to the script.

Maybe as a safety measure, if the output filename would be `/home/user/output.mp4`, for example, and that file already exists, we instead output to `/home/user/output.clip.mp4` to prevent overwriting the original video.

If you feel like implementing these changes I'd appreciate it, just let me know. If not, I may just merge this PR anyway and then make those changes myself afterwards.

Thanks again for the PRs! Happy to see someone else finding my little script useful. :)

**Comment by ernstwi** [comment]
Sure, I'll give it a try! Sounds good.

When output-file is a directory, would you still like to use `$filename $start_time.$extension` as the output filename? I think that would be the best way to do it.

**Comment by ernstwi** [comment]
With this change the script infers output format from the `output-file` argument. If `output-file` is a directory, `$input_filename $start_time.$extension` is used as the filename.

I'll skip implementing the added safety measure you suggested for now if that's ok. Since the start time of the loop is appended to the output filename when the script is invoked from mpv I think the risk of overwriting is pretty small.

**Comment by defaultxr** [comment]
Looks good, thank you! :)

**Pull request merged**
